---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workshop-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: http
  selector:
    {{- include "workshop-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workshop-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workshop-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "workshop-operator.selectorLabels" . | nindent 4 }}