{{- if .Values.webhook.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "workshop-operator.fullname" . }}-serving-cert
  creationTimestamp: null
  name: {{ include "workshop-operator.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      service:
        name: {{ include "workshop-operator.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-workshop-stakater-com-v1alpha1-channel
    failurePolicy: Fail
    sideEffects: None
    name: vchannel.kb.io
    rules:
    - apiGroups:
      - slack.stakater.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - channels
{{- end -}}

