apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: workshop-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Workshop is the Schema for the workshops API
      displayName: Workshop
      kind: Workshop
      name: workshops.workshop.stakater.com
      version: v1
  description: A Kubernetes Operator to install the infrastructure for running workshops/bootcamps on OpenShift.
  displayName: workshop-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - workshop
  links:
  - name: Workshop Operator
    url: https://workshop-operator.domain
  maturity: alpha
  provider:
    name: stakater
    url: https://stakater.com
  version: 0.0.0
