name: Push

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - config/samples/**
env:
  DOCKER_FILE_PATH: Dockerfile
  GOLANG_VERSION: 1.16
  KUBERNETES_VERSION: "1.20.2"
  KIND_VERSION: "0.10.0"
  GO111MODULE: on
  CGO_ENABLED : 0

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: Set up Go
        id: go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Cache Clean
        run: |
          golangci-lint cache clean

      - name: Lint
        uses: golangci/golangci-lint-action@v2.3.0
        with:
          version: v1.39.0
          only-new-issues: false
          args: --timeout 10m
          skip-pkg-cache: true
          skip-build-cache: true


        golangci-lint cache clean